In [28]:
import pandas as pd

In [29]:
df = pd.read_csv("/content/student_performance_large_dataset.csv")
df.head()

,Student_ID,Name,Gender,Class,Math,Science,English,Computer,Social_Studies
0,1001,Student_1,Male,11A,50,76,97,88,92
1,1002,Student_2,Female,11A,71,59,75,82,49
2,1003,Student_3,Male,12B,58,75,36,80,76
3,1004,Student_4,Male,11B,60,75,62,75,52
4,1005,Student_5,Male,11A,54,37,50,75,72

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student_ID      10000 non-null  int64
 1   Name            10000 non-null  object
 2   Gender          10000 non-null  object
 3   Class           10000 non-null  object
 4   Math            10000 non-null  int64
 5   Science         10000 non-null  int64
 6   English         10000 non-null  int64
 7   Computer        10000 non-null  int64
 8   Social_Studies  10000 non-null  int64
dtypes: int64(6), object(3)
memory usage: 703.3+ KB

In [31]:
df.describe()

,Student_ID,Math,Science,English,Computer,Social_Studies
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,6000.50000,67.304600,67.634400,67.173700,67.329600,67.428800
std,2886.89568,19.135199,18.980652,19.183074,19.040379,19.071862
min,1001.00000,35.000000,35.000000,35.000000,35.000000,35.000000
25%,3500.75000,50.000000,51.000000,51.000000,51.000000,51.000000
50%,6000.50000,67.000000,68.000000,67.000000,67.000000,67.000000
75%,8500.25000,84.000000,84.000000,84.000000,84.000000,84.000000
max,11000.00000,100.000000,100.000000,100.000000,100.000000,100.000000

In [32]:
df.isnull().sum()

Student_ID        0
Name              0
Gender            0
Class             0
Math              0
Science           0
English           0
Computer          0
Social_Studies    0
dtype: int64

In [33]:
df['Total'] = df[['Math','Science','English','Computer','Social_Studies']].sum(axis=1)

df.head()

,Student_ID,Name,Gender,Class,Math,Science,English,Computer,Social_Studies,Total
0,1001,Student_1,Male,11A,50,76,97,88,92,403
1,1002,Student_2,Female,11A,71,59,75,82,49,336
2,1003,Student_3,Male,12B,58,75,36,80,76,325
3,1004,Student_4,Male,11B,60,75,62,75,52,324
4,1005,Student_5,Male,11A,54,37,50,75,72,288

In [34]:
df['Average'] = df['Total']/5

df.head()

,Student_ID,Name,Gender,Class,Math,Science,English,Computer,Social_Studies,Total,Average
0,1001,Student_1,Male,11A,50,76,97,88,92,403,80.6
1,1002,Student_2,Female,11A,71,59,75,82,49,336,67.2
2,1003,Student_3,Male,12B,58,75,36,80,76,325,65.0
3,1004,Student_4,Male,11B,60,75,62,75,52,324,64.8
4,1005,Student_5,Male,11A,54,37,50,75,72,288,57.6

In [35]:
top_10 = df.sort_values(by='Average',ascending=False)

top_10.head(10)

,Student_ID,Name,Gender,Class,Math,Science,English,Computer,Social_Studies,Total,Average
5035,6036,Student_5036,Female,10B,99,89,99,93,99,479,95.8
4371,5372,Student_4372,Female,10A,99,94,83,97,98,471,94.2
294,1295,Student_295,Female,10A,83,100,100,100,85,468,93.6
8882,9883,Student_8883,Female,11B,97,96,98,99,77,467,93.4
6998,7999,Student_6999,Male,11B,97,96,91,88,95,467,93.4
8526,9527,Student_8527,Female,11B,97,91,98,93,86,465,93.0
6194,7195,Student_6195,Male,10B,92,87,100,92,94,465,93.0
2056,3057,Student_2057,Female,12A,96,82,89,98,97,462,92.4
4891,5892,Student_4892,Female,12A,86,97,94,87,97,461,92.2
8518,9519,Student_8519,Male,10B,100,97,98,95,71,461,92.2

In [36]:
top_10[['Name','Average']].head(10)

              Name  Average
5035  Student_5036     95.8
4371  Student_4372     94.2
294    Student_295     93.6
8882  Student_8883     93.4
6998  Student_6999     93.4
8526  Student_8527     93.0
6194  Student_6195     93.0
2056  Student_2057     92.4
4891  Student_4892     92.2
8518  Student_8519     92.2

In [37]:
df.loc[df['Math'].idxmax()]

Student_ID              1027
Name              Student_27
Gender                Female
Class                    12B
Math                     100
Science                   64
English                   57
Computer                  43
Social_Studies            76
Total                    340
Average                 68.0
Name: 26, dtype: object

In [38]:
df.loc[df['Science'].idxmax()]

Student_ID              1019
Name              Student_19
Gender                Female
Class                    12A
Math                      57
Science                  100
English                   62
Computer                  89
Social_Studies            87
Total                    395
Average                 79.0
Name: 18, dtype: object

In [39]:
print("Math Highest =",df['Math'].max())
print("Science Highest =",df['Science'].max())
print("English Highest =",df['English'].max())
print("Computer Highest =",df['Computer'].max())
print("Social Studies Highest =",df['Social_Studies'].max())

Math Highest = 100
Science Highest = 100
English Highest = 100
Computer Highest = 100
Social Studies Highest = 100

In [40]:
def grade(avg):
    if avg >= 90:
        return 'A'
    elif avg >= 80:
        return 'B'
    elif avg >= 70:
        return 'C'
    elif avg >= 60:
        return 'D'
    else:
        return 'F'

In [41]:
df['Grade'] = df['Average'].apply(grade)

df.head()

,Student_ID,Name,Gender,Class,Math,Science,English,Computer,Social_Studies,Total,Average,Grade
0,1001,Student_1,Male,11A,50,76,97,88,92,403,80.6,B
1,1002,Student_2,Female,11A,71,59,75,82,49,336,67.2,D
2,1003,Student_3,Male,12B,58,75,36,80,76,325,65.0,D
3,1004,Student_4,Male,11B,60,75,62,75,52,324,64.8,D
4,1005,Student_5,Male,11A,54,37,50,75,72,288,57.6,F

In [42]:
df['Grade'].value_counts()

Grade
D    4127
C    3155
F    1985
B     706
A      27
Name: count, dtype: int64

In [43]:
df.groupby('Grade')['Student_ID'].count()

Grade
A      27
B     706
C    3155
D    4127
F    1985
Name: Student_ID, dtype: int64

In [44]:
df.groupby('Class')['Average'].mean()

Class
10A    67.510751
10B    67.656617
11A    67.223352
11B    67.677412
12A    67.287390
12B    66.861472
Name: Average, dtype: float64

In [45]:
df.groupby('Gender')['Average'].mean()

Gender
Female    67.320473
Male      67.427688
Name: Average, dtype: float64

In [46]:
df.describe()

,Student_ID,Math,Science,English,Computer,Social_Studies,Total,Average
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,6000.50000,67.304600,67.634400,67.173700,67.329600,67.428800,336.871100,67.374220
std,2886.89568,19.135199,18.980652,19.183074,19.040379,19.071862,43.291012,8.658202
min,1001.00000,35.000000,35.000000,35.000000,35.000000,35.000000,188.000000,37.600000
25%,3500.75000,50.000000,51.000000,51.000000,51.000000,51.000000,307.000000,61.400000
50%,6000.50000,67.000000,68.000000,67.000000,67.000000,67.000000,337.000000,67.400000
75%,8500.25000,84.000000,84.000000,84.000000,84.000000,84.000000,367.000000,73.400000
max,11000.00000,100.000000,100.000000,100.000000,100.000000,100.000000,479.000000,95.800000